export const user = {
    email: 'pvl.sever.kz@gmail.com',
    password: '5o67902#h&fKFWQv',
    incorrectemail: 'm.orynbay@srgdev.kz1',
    incorrectpassword: 'errorpassword',
    testemail: 'xwkogypfnfztqalfyz@bvhrk.com',
    testCamera: 'Тест ПТЗ',
    deletedemail: 'cijpqxmmb@firste.ml',
    deletedpassword: '@O304!1uboea7P5H',
    blockedemail: 'jfvwthjsb@supere.ml',
    blockedpassword: '9F8oC5np2c7[&4rx',
    noValueemail: '',
    noValuepassword: '',
    cyrillicemail:'пвл.север.кз@gmail.com',
    specsymbolemail: '!@#$%$%^&*(',
    symbolemail: 'pvl.sever.kzgmail.com',
    emailnotdomain: 'pvl.sever.kz@',
    adminemail: 'vms-admin@sergdev.kz',
    adminpassword: '1q2w3e',
    passwordcyrillic: 'ыфафыафыа',
    passwordlatin: 'qwertyuiop',
    passwordspecsymbol: '!@#$%^&*()_+',
    emailnumber: '1234567890',
    
};
export const OrganizationClient = {
    titleOrg:'МВД РК',
    binOrg:'101010101011',
    titleObj:'КУИС',
    binObj:'101010101012',
    titleCam:'PTZ-FOR-USE',
    ipCam:'172.27.211.250',
    testText: 'testMiras', 

}